# Generated by Django 4.2.2 on 2023-11-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automax', '0002_listing_brand_listing_color_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-updated_at',)},
        ),
    ]
